# Generated by Django 4.2.5 on 2023-09-08 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('splittify', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='owers',
            field=models.ManyToManyField(related_name='user_is_ower', through='splittify.Transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bill',
            name='payer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_is_payer', to=settings.AUTH_USER_MODEL),
        ),
    ]
