# Generated by Django 4.2.5 on 2023-09-08 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('splittify', '0003_remove_transactions_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='splitways',
            options={'verbose_name_plural': 'SplitWays'},
        ),
        migrations.AlterModelOptions(
            name='transactions',
            options={'verbose_name_plural': 'Transactions'},
        ),
        migrations.AlterField(
            model_name='transactions',
            name='bill_ower',
            field=models.ForeignKey(limit_choices_to={'trip__users': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
